spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TestWork?user=mysql&password=mysql&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    hikari:
      max-lifetime: 600000
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: false